import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import NavBar from "./components/NavBar";

const dm_Sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-idm-sans',
})

export const metadata: Metadata = {
  title: "Aurora ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dm_Sans.variable} `}>
      <link rel="icon" href="/auroraicon.png" />
      <body  className="bg-[#070815]">
        <Providers>
        <NavBar />
        {children}
        </Providers>
        </body>
    </html>
  );
}
